@extends('layouts.app')
@section('title','Dashboard') @section('page_title','Dashboard')
@section('content')
<div class="space-y-6"><div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 class="text-3xl font-extrabold text-slate-900">Good {{ now()->hour < 12 ? 'morning' : (now()->hour < 17 ? 'afternoon' : 'evening') }}, {{ Str::before(Auth::user()->name, ' ') }}.</h2><p class="mt-1 text-slate-500">Here is what is happening across your school today.</p></div><div class="flex gap-3"><a href="{{ route('students.create') }}" class="rounded-xl bg-[#06322C] px-5 py-3 text-sm font-bold text-white hover:bg-[#08423B]">+ Add student</a><a href="{{ route('reports.index') }}" class="rounded-xl border border-[#06322C] px-5 py-3 text-sm font-bold text-[#06322C]">View reports</a></div></div>
@php($cards=[['Students',$stats['total_students'],'students.index'],['Teachers',$stats['total_teachers'],'teachers.index'],['Classes',$stats['total_classes'],'classes.index'],['Subjects',$stats['total_subjects'],'subjects.index']])
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach($cards as $i=>$card)<a href="{{ route($card[2]) }}" class="rounded-2xl border border-slate-100 p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-md {{ $i===0 ? 'bg-[#06322C] text-white' : 'bg-white' }}"><div class="flex items-start justify-between"><p class="text-sm {{ $i===0 ? 'text-[#7ED3C4]' : 'text-slate-500' }}">Total {{ $card[0] }}</p><span class="grid h-8 w-8 place-items-center rounded-full {{ $i===0 ? 'bg-white/10' : 'bg-[#7ED3C4]/20 text-[#06322C]' }}">↗</span></div><strong class="mt-4 block text-4xl">{{ number_format($card[1]) }}</strong><p class="mt-3 text-xs {{ $i===0 ? 'text-slate-300' : 'text-slate-400' }}">Open {{ strtolower($card[0]) }} workspace</p></a>@endforeach</div>
<div class="grid gap-6 xl:grid-cols-[1.45fr_.85fr]"><section class="rounded-2xl bg-white p-6 shadow-sm"><div class="flex items-center justify-between"><div><h3 class="font-bold text-slate-900">Enrollment overview</h3><p class="text-sm text-slate-400">New students in {{ date('Y') }}</p></div><a href="{{ route('students.index') }}" class="text-sm font-bold text-[#3A7B72]">All students</a></div><div class="mt-5 h-64"><canvas id="enrollmentChart"></canvas></div></section>
<section class="rounded-2xl bg-[#06322C] p-6 text-white shadow-sm"><p class="text-sm text-[#7ED3C4]">Finance snapshot</p><h3 class="mt-4 text-3xl font-extrabold">₦{{ number_format($stats['total_revenue'],2) }}</h3><p class="text-sm text-slate-300">Total collected</p><div class="my-6 h-px bg-white/10"></div><div class="flex justify-between"><span class="text-slate-300">Outstanding</span><strong>₦{{ number_format($stats['pending_payments'],2) }}</strong></div><a href="{{ route('payments.index') }}" class="mt-8 block rounded-xl bg-[#7ED3C4] py-3 text-center text-sm font-bold text-[#06322C]">Manage finance</a></section></div>
<div class="grid gap-6 xl:grid-cols-2"><section class="rounded-2xl bg-white p-6 shadow-sm"><div class="flex justify-between"><h3 class="font-bold">Recent students</h3><a href="{{ route('students.index') }}" class="text-sm font-bold text-[#3A7B72]">View all</a></div><div class="mt-4 divide-y">@forelse($recentStudents->take(5) as $student)<a href="{{ route('students.show',$student) }}" class="flex items-center gap-3 py-3 hover:bg-slate-50"><span class="grid h-9 w-9 place-items-center rounded-full bg-[#7ED3C4]/30 font-bold text-[#06322C]">{{ substr($student->first_name,0,1) }}{{ substr($student->last_name,0,1) }}</span><span class="flex-1"><strong class="block text-sm">{{ $student->full_name }}</strong><small class="text-slate-400">{{ $student->class->full_name ?? 'Class not assigned' }}</small></span><span class="text-slate-300">→</span></a>@empty<p class="py-10 text-center text-sm text-slate-400">No students yet. Add your first student.</p>@endforelse</div></section>
<section class="rounded-2xl bg-white p-6 shadow-sm"><div class="flex justify-between"><h3 class="font-bold">Recent payments</h3><a href="{{ route('payments.index') }}" class="text-sm font-bold text-[#3A7B72]">View all</a></div><div class="mt-4 divide-y">@forelse($recentPayments->take(5) as $payment)<a href="{{ route('payments.show',$payment) }}" class="flex items-center gap-3 py-3 hover:bg-slate-50"><span class="grid h-9 w-9 place-items-center rounded-full bg-slate-100 text-[#3A7B72]">₦</span><span class="flex-1"><strong class="block text-sm">{{ $payment->student->full_name ?? 'Student' }}</strong><small class="text-slate-400">{{ $payment->invoice_number }}</small></span><span class="text-right"><strong class="block text-sm">₦{{ number_format($payment->amount) }}</strong><small class="{{ $payment->status==='paid' ? 'text-emerald-600':'text-amber-600' }}">{{ ucfirst($payment->status) }}</small></span></a>@empty<p class="py-10 text-center text-sm text-slate-400">No payments recorded yet.</p>@endforelse</div></section></div></div>
@push('scripts')<script>new Chart(document.getElementById('enrollmentChart'),{type:'bar',data:{labels:{!! json_encode($monthlyEnrollment->pluck('month')->map(fn($m)=>date('M',mktime(0,0,0,$m,1)))) !!},datasets:[{data:{!! json_encode($monthlyEnrollment->pluck('count')) !!},backgroundColor:'#3A7B72',borderRadius:8,barThickness:22}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false},border:{display:false}},y:{beginAtZero:true,ticks:{precision:0},grid:{color:'#eef2f1'},border:{display:false}}}}});</script>@endpush
@endsection
