@extends('layouts.app')
@section('title','Planning') @section('page_title','Homework & Events')
@section('content')
<div class="space-y-6" x-data="{tab:'homework'}">
 <div><h2 class="text-3xl font-extrabold text-[#06322C]">Academic planning</h2><p class="text-slate-500">Publish homework and keep families informed about upcoming school events.</p></div>
 @if(session('success'))<div class="rounded-xl bg-emerald-50 p-4 text-sm font-bold text-emerald-700">{{session('success')}}</div>@endif
 @if($errors->any())<div class="rounded-xl bg-red-50 p-4 text-sm text-red-700"><strong>Nothing was saved.</strong><ul class="mt-1 list-disc pl-5">@foreach($errors->all() as $error)<li>{{$error}}</li>@endforeach</ul></div>@endif
 <div class="flex gap-2"><button @click="tab='homework'" :class="tab==='homework'?'bg-[#06322C] text-white':'bg-white text-slate-600'" class="rounded-xl px-4 py-2 font-bold">Homework</button><button @click="tab='events'" :class="tab==='events'?'bg-[#06322C] text-white':'bg-white text-slate-600'" class="rounded-xl px-4 py-2 font-bold">Events</button></div>
 <section x-show="tab==='homework'" class="grid gap-6 lg:grid-cols-[380px_1fr]">
  <form method="POST" action="{{ route('planning.homework.store') }}" class="space-y-3 rounded-2xl bg-white p-6 shadow-sm">@csrf<h3 class="font-extrabold">New homework</h3><input name="title" required placeholder="Title" class="w-full rounded-xl"><div class="grid grid-cols-2 gap-2"><select name="class_id" required class="rounded-xl"><option value="">Class</option>@foreach($classes as $class)<option value="{{$class->id}}">{{$class->full_name}}</option>@endforeach</select><select name="subject_id" required class="rounded-xl"><option value="">Subject</option>@foreach($subjects as $subject)<option value="{{$subject->id}}">{{$subject->name}}</option>@endforeach</select></div><textarea name="instructions" required rows="4" placeholder="Instructions" class="w-full rounded-xl"></textarea><input type="datetime-local" name="due_at" required class="w-full rounded-xl"><label class="flex gap-2 text-sm"><input type="checkbox" name="publish_now" value="1" checked> Publish now</label><button class="w-full rounded-xl bg-[#06322C] py-3 font-bold text-white">Save homework</button></form>
  <div class="space-y-3">@forelse($homework as $item)<article class="rounded-2xl bg-white p-5 shadow-sm"><div class="flex justify-between gap-3"><div><h3 class="font-extrabold text-[#06322C]">{{$item->title}}</h3><p class="text-sm text-slate-500">{{$item->subject?->name}} · {{$item->class?->full_name}}</p></div><span class="text-xs font-bold text-slate-500">Due {{$item->due_at->format('M j, g:i A')}}</span></div><p class="mt-3 text-sm">{{$item->instructions}}</p></article>@empty<p class="rounded-2xl bg-white p-10 text-center text-slate-400">No homework yet.</p>@endforelse {{$homework->links()}}</div>
 </section>
 <section x-show="tab==='events'" class="grid gap-6 lg:grid-cols-[380px_1fr]">
  <form method="POST" action="{{ route('planning.events.store') }}" class="space-y-3 rounded-2xl bg-white p-6 shadow-sm">@csrf<h3 class="font-extrabold">New event</h3><input name="title" required placeholder="Event title" class="w-full rounded-xl"><textarea name="description" rows="3" placeholder="Description" class="w-full rounded-xl"></textarea><select name="audience" class="w-full rounded-xl"><option value="all">Everyone</option><option value="parents">Parents</option><option value="students">Students</option><option value="teachers">Teachers</option></select><input type="datetime-local" name="starts_at" required class="w-full rounded-xl"><input type="datetime-local" name="ends_at" class="w-full rounded-xl"><input name="location" placeholder="Location" class="w-full rounded-xl"><button class="w-full rounded-xl bg-[#06322C] py-3 font-bold text-white">Create event</button></form>
  <div class="space-y-3">@forelse($events as $event)<article class="rounded-2xl bg-white p-5 shadow-sm"><h3 class="font-extrabold text-[#06322C]">{{$event->title}}</h3><p class="text-sm text-slate-500">{{$event->starts_at->format('M j, Y · g:i A')}} · {{$event->location ?: 'School event'}}</p><p class="mt-3 text-sm">{{$event->description}}</p></article>@empty<p class="rounded-2xl bg-white p-10 text-center text-slate-400">No upcoming events.</p>@endforelse {{$events->links()}}</div>
 </section>
</div>
@endsection
