@extends('layouts.app')
@section('title','AI Assistant')
@section('page_title','AI Assistant')
@section('content')
<div class="space-y-6" x-data="{tool:'lesson_plan'}">
 <div><h2 class="text-3xl font-extrabold text-[#06322C]">SchoolOS Copilot</h2><p class="text-slate-500">Create educator-reviewed drafts from structured school context.</p></div>
 @if($errors->any())<div class="rounded-xl bg-red-50 p-4 text-red-700">{{ $errors->first() }}</div>@endif
 <div class="grid gap-2 sm:grid-cols-4">@foreach(['lesson_plan'=>'Lesson plan','exam_questions'=>'Exam questions','report_comment'=>'Report comment','principal_summary'=>'Principal brief'] as $key=>$label)@if($key!=='principal_summary'||Auth::user()->role==='school_admin')<button @click="tool='{{ $key }}'" :class="tool==='{{ $key }}'?'bg-[#06322C] text-white':'bg-white text-slate-600'" class="rounded-xl px-4 py-3 text-sm font-bold">{{ $label }}</button>@endif @endforeach</div>
 <form x-show="tool==='lesson_plan'" method="POST" action="{{ route('ai.store') }}" class="grid gap-4 rounded-2xl bg-white p-6 shadow-sm md:grid-cols-2">@csrf<input type="hidden" name="type" value="lesson_plan"><h3 class="text-xl font-extrabold md:col-span-2">Draft a lesson plan</h3><input name="subject" required placeholder="Subject" class="rounded-xl border border-slate-300"><input name="class_level" required placeholder="Class level" class="rounded-xl border border-slate-300"><input name="topic" required placeholder="Topic" class="rounded-xl border border-slate-300"><input type="number" name="duration_minutes" value="45" min="10" max="240" class="rounded-xl border border-slate-300"><textarea name="learning_context" placeholder="Curriculum goals, available resources, learner needs (no sensitive data)" class="rounded-xl border border-slate-300 md:col-span-2"></textarea><button class="rounded-xl bg-[#06322C] py-3 font-bold text-white md:col-span-2">Generate reviewed draft</button></form>
 <form x-show="tool==='exam_questions'" method="POST" action="{{ route('ai.store') }}" class="grid gap-4 rounded-2xl bg-white p-6 shadow-sm md:grid-cols-2">@csrf<input type="hidden" name="type" value="exam_questions"><h3 class="text-xl font-extrabold md:col-span-2">Draft question bank items</h3><input name="subject" required placeholder="Subject" class="rounded-xl border border-slate-300"><input name="class_level" required placeholder="Class level" class="rounded-xl border border-slate-300"><input name="topic" required placeholder="Topic" class="rounded-xl border border-slate-300"><input type="number" name="question_count" value="5" min="1" max="20" class="rounded-xl border border-slate-300"><select name="difficulty" class="rounded-xl border border-slate-300"><option>mixed</option><option>easy</option><option>medium</option><option>hard</option></select><textarea name="curriculum_notes" placeholder="Learning outcomes and curriculum constraints" class="rounded-xl border border-slate-300"></textarea><button class="rounded-xl bg-[#06322C] py-3 font-bold text-white md:col-span-2">Generate question drafts</button></form>
 <form x-show="tool==='report_comment'" method="POST" action="{{ route('ai.store') }}" class="grid gap-4 rounded-2xl bg-white p-6 shadow-sm md:grid-cols-2">@csrf<input type="hidden" name="type" value="report_comment"><h3 class="text-xl font-extrabold md:col-span-2">Draft an evidence-based report comment</h3><input name="subject" required placeholder="Subject" class="rounded-xl border border-slate-300"><input name="class_level" required placeholder="Class level" class="rounded-xl border border-slate-300"><input type="number" name="score_percentage" min="0" max="100" step="0.01" required placeholder="Score percentage" class="rounded-xl border border-slate-300"><select name="teacher_tone" class="rounded-xl border border-slate-300"><option>encouraging</option><option>formal</option><option>concise</option></select><textarea name="performance_evidence" required placeholder="Observed strengths, misconceptions, and completed work. Do not include the student's name." class="rounded-xl border border-slate-300 md:col-span-2"></textarea><button class="rounded-xl bg-[#06322C] py-3 font-bold text-white md:col-span-2">Generate comment draft</button></form>
 @if(Auth::user()->role==='school_admin')<form x-show="tool==='principal_summary'" method="POST" action="{{ route('ai.store') }}" class="rounded-2xl bg-[#06322C] p-7 text-white shadow-sm">@csrf<input type="hidden" name="type" value="principal_summary"><h3 class="text-xl font-extrabold">Generate weekly principal brief</h3><p class="mt-2 text-sm text-emerald-100">SchoolOS supplies aggregate enrollment, attendance, finance, and student-risk metrics. No student-level personal data is sent.</p><button class="mt-5 rounded-xl bg-[#7ED3C4] px-5 py-3 font-bold text-[#06322C]">Generate executive brief</button></form>@endif
 <div class="overflow-hidden rounded-2xl bg-white shadow-sm"><h3 class="p-6 text-lg font-extrabold">Generation history</h3><table class="w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-400"><tr><th class="p-4">Tool</th><th>Requested</th><th>Status</th><th>Model</th></tr></thead><tbody class="divide-y">@forelse($requests as $item)<tr><td class="p-4"><a href="{{ route('ai.show',$item) }}" class="font-bold text-[#06322C]">{{ ucfirst(str_replace('_',' ',$item->type)) }}</a></td><td>{{ $item->created_at->diffForHumans() }}</td><td>{{ ucfirst($item->status) }}</td><td>{{ $item->model??'—' }}</td></tr>@empty<tr><td colspan="4" class="p-10 text-center text-slate-400">No copilot generations yet.</td></tr>@endforelse</tbody></table></div>{{ $requests->links() }}
</div>
@endsection
