[program:schoolos-horizon]
process_name=%(program_name)s
command=php /var/www/schoolos/current/artisan horizon
directory=/var/www/schoolos/current
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/log/supervisor/schoolos-horizon.log
stopwaitsecs=3600

[program:schoolos-scheduler]
command=php /var/www/schoolos/current/artisan schedule:work
directory=/var/www/schoolos/current
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/log/supervisor/schoolos-scheduler.log
