@extends('layouts.app')
@section('title','Parents') @section('page_title','Parents')
@section('content')
<div class="space-y-6" x-data="{create:false, editing:null}">
 <div class="flex items-end justify-between"><div><h2 class="text-3xl font-extrabold text-[#06322C]">Parent accounts</h2><p class="text-slate-500">Create login credentials and connect each parent to their children.</p></div><button @click="create=!create" class="rounded-xl bg-[#06322C] px-5 py-3 font-bold text-white">+ Add parent</button></div>
 <form x-show="create" method="POST" action="{{ route('parents.store') }}" class="grid gap-4 rounded-2xl bg-white p-6 shadow-sm md:grid-cols-2">@csrf
  <h3 class="text-xl font-extrabold md:col-span-2">New parent account</h3>
  <input name="name" value="{{ old('name') }}" required placeholder="Full name" class="rounded-xl border border-slate-300 px-4 py-3 focus:border-[#3A7B72] focus:ring-[#3A7B72]"><input name="phone" value="{{ old('phone') }}" required placeholder="Phone number" class="rounded-xl border border-slate-300 px-4 py-3 focus:border-[#3A7B72] focus:ring-[#3A7B72]">
  <input type="email" name="email" value="{{ old('email') }}" required placeholder="Login email" class="rounded-xl border border-slate-300 px-4 py-3 focus:border-[#3A7B72] focus:ring-[#3A7B72]"><select name="relationship" class="rounded-xl border border-slate-300 px-4 py-3 focus:border-[#3A7B72] focus:ring-[#3A7B72]"><option value="mother">Mother</option><option value="father">Father</option><option value="guardian">Guardian</option><option value="other">Other</option></select>
  <input type="password" name="password" minlength="8" required placeholder="Password" class="rounded-xl border border-slate-300 px-4 py-3 focus:border-[#3A7B72] focus:ring-[#3A7B72]"><input type="password" name="password_confirmation" minlength="8" required placeholder="Confirm password" class="rounded-xl border border-slate-300 px-4 py-3 focus:border-[#3A7B72] focus:ring-[#3A7B72]">
  <label class="md:col-span-2 text-sm font-bold text-slate-600">Associated students<select name="student_ids[]" required multiple size="6" class="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 focus:border-[#3A7B72] focus:ring-[#3A7B72]">@foreach($students as $student)<option value="{{ $student->id }}">{{ $student->full_name }} · {{ $student->admission_number }} · {{ $student->class?->name ?? 'No class' }}</option>@endforeach</select><small class="font-normal text-slate-400">Hold Ctrl/Cmd to select multiple children.</small></label>
  @if($errors->any())<div class="rounded-xl bg-red-50 p-3 text-red-700 md:col-span-2">{{ $errors->first() }}</div>@endif
  <button class="rounded-xl bg-[#06322C] py-3 font-bold text-white md:col-span-2">Create parent login</button>
 </form>
 <div class="overflow-x-auto rounded-2xl bg-white shadow-sm"><table class="w-full min-w-[900px] text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-400"><tr><th class="p-4">Parent</th><th>Contact</th><th>Linked students</th><th>Created</th><th class="pr-4 text-right">Action</th></tr></thead><tbody class="divide-y">@forelse($parents as $parent)<tr><td class="p-4 font-bold text-[#06322C]">{{ $parent->name }}</td><td>{{ $parent->email }}<small class="block text-slate-400">{{ $parent->phone }}</small></td><td>@forelse($parent->children as $child)<span class="mr-1 inline-block rounded-full bg-emerald-50 px-3 py-1 text-xs text-emerald-700">{{ $child->full_name }}</span>@empty<span class="text-amber-600">Not linked</span>@endforelse</td><td>{{ $parent->created_at->format('M j, Y') }}</td><td class="pr-4 text-right"><button type="button" @click="editing = editing === {{ $parent->id }} ? null : {{ $parent->id }}" class="rounded-lg border border-slate-200 px-3 py-2 font-bold text-[#3A7B72] hover:border-[#3A7B72]" x-text="editing === {{ $parent->id }} ? 'Close' : 'Edit'"></button></td></tr>
 <tr x-show="editing === {{ $parent->id }}" x-cloak><td colspan="5" class="bg-slate-50 p-5"><form method="POST" action="{{ route('parents.update', $parent) }}" class="grid gap-4 rounded-2xl border border-slate-200 bg-white p-5 md:grid-cols-2">@csrf @method('PUT')
  <div class="md:col-span-2"><h3 class="text-lg font-extrabold text-[#06322C]">Edit {{ $parent->name }}</h3><p class="text-xs text-slate-500">Update the account or assign additional children from this school.</p></div>
  <input name="name" value="{{ $parent->name }}" required placeholder="Full name" class="rounded-xl border border-slate-300 px-4 py-3"><input name="phone" value="{{ $parent->phone }}" required placeholder="Phone number" class="rounded-xl border border-slate-300 px-4 py-3">
  <input type="email" name="email" value="{{ $parent->email }}" required placeholder="Login email" class="rounded-xl border border-slate-300 px-4 py-3"><select name="relationship" class="rounded-xl border border-slate-300 px-4 py-3">@foreach(['mother'=>'Mother','father'=>'Father','guardian'=>'Guardian','other'=>'Other'] as $value=>$label)<option value="{{ $value }}" @selected(($parent->children->first()?->pivot?->relationship ?? 'guardian') === $value)>{{ $label }}</option>@endforeach</select>
  <input type="password" name="password" minlength="8" placeholder="New password (optional)" class="rounded-xl border border-slate-300 px-4 py-3"><input type="password" name="password_confirmation" minlength="8" placeholder="Confirm new password" class="rounded-xl border border-slate-300 px-4 py-3">
  <label class="md:col-span-2 text-sm font-bold text-slate-600">Associated students<select name="student_ids[]" required multiple size="7" class="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3">@foreach($students as $student)<option value="{{ $student->id }}" @selected($parent->children->contains('id', $student->id))>{{ $student->full_name }} · {{ $student->admission_number }} · {{ $student->class?->name ?? 'No class' }}</option>@endforeach</select><small class="font-normal text-slate-400">Current children are selected. Hold Ctrl/Cmd to add or remove children.</small></label>
  <button class="rounded-xl bg-[#06322C] py-3 font-bold text-white md:col-span-2">Save parent and student links</button>
 </form></td></tr>@empty<tr><td colspan="5" class="p-12 text-center text-slate-400">No parent accounts yet.</td></tr>@endforelse</tbody></table></div>{{ $parents->links() }}
</div>
@endsection
