<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{
 public function up():void{
  Schema::create('grading_policies',function(Blueprint $t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->string('name');$t->unsignedInteger('version')->default(1);$t->boolean('is_active')->default(false);$t->timestamps();$t->unique(['school_id','name','version']);$t->index(['school_id','is_active']);});
  Schema::create('grading_bands',function(Blueprint $t){$t->id();$t->foreignId('grading_policy_id')->constrained()->cascadeOnDelete();$t->decimal('minimum_percentage',5,2);$t->decimal('maximum_percentage',5,2);$t->string('letter_grade',5);$t->decimal('grade_point',4,2);$t->string('remark',100)->nullable();$t->timestamps();$t->index(['grading_policy_id','minimum_percentage']);});
  Schema::create('assessments',function(Blueprint $t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->foreignId('academic_term_id')->constrained()->cascadeOnDelete();$t->foreignId('class_id')->constrained('classes')->cascadeOnDelete();$t->foreignId('subject_id')->constrained()->cascadeOnDelete();$t->foreignId('teacher_id')->constrained('users')->restrictOnDelete();$t->string('title');$t->string('type',30);$t->decimal('maximum_score',8,2);$t->decimal('weight_percentage',5,2);$t->date('assessment_date')->nullable();$t->string('status',20)->default('draft');$t->foreignId('approved_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('approved_at')->nullable();$t->timestamps();$t->index(['school_id','academic_term_id','class_id','subject_id']);});
  Schema::create('assessment_scores',function(Blueprint $t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->foreignId('assessment_id')->constrained()->cascadeOnDelete();$t->foreignId('student_id')->constrained()->cascadeOnDelete();$t->decimal('score',8,2);$t->text('teacher_comment')->nullable();$t->foreignId('entered_by')->constrained('users')->restrictOnDelete();$t->timestamps();$t->unique(['assessment_id','student_id']);$t->index(['school_id','student_id']);});
  Schema::create('transcripts',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->foreignId('student_id')->constrained()->cascadeOnDelete();$t->foreignId('grading_policy_id')->constrained()->restrictOnDelete();$t->decimal('cgpa',5,2)->nullable();$t->json('snapshot');$t->string('status',20)->default('issued');$t->foreignId('issued_by')->constrained('users')->restrictOnDelete();$t->timestamp('issued_at');$t->timestamp('revoked_at')->nullable();$t->text('revocation_reason')->nullable();$t->timestamps();$t->index(['school_id','student_id','issued_at']);});
 }
 public function down():void{Schema::dropIfExists('transcripts');Schema::dropIfExists('assessment_scores');Schema::dropIfExists('assessments');Schema::dropIfExists('grading_bands');Schema::dropIfExists('grading_policies');}
};
