<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up():void{
  Schema::create('fee_invoices',function(Blueprint $t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->foreignId('student_id')->constrained()->cascadeOnDelete();$t->foreignId('academic_term_id')->nullable()->constrained()->nullOnDelete();$t->string('invoice_number')->unique();$t->char('currency',3)->default('NGN');$t->decimal('subtotal',14,2)->default(0);$t->decimal('discount_total',14,2)->default(0);$t->decimal('amount_due',14,2)->default(0);$t->decimal('amount_paid',14,2)->default(0);$t->string('status',20)->default('draft');$t->date('due_on')->nullable();$t->timestamp('issued_at')->nullable();$t->foreignId('created_by')->constrained('users')->restrictOnDelete();$t->timestamps();$t->index(['school_id','status','due_on']);});
  Schema::create('fee_invoice_items',function(Blueprint $t){$t->id();$t->foreignId('fee_invoice_id')->constrained()->cascadeOnDelete();$t->string('description');$t->unsignedInteger('quantity')->default(1);$t->decimal('unit_amount',14,2);$t->decimal('total_amount',14,2);$t->timestamps();});
  Schema::create('installment_schedules',function(Blueprint $t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->foreignId('fee_invoice_id')->constrained()->cascadeOnDelete();$t->unsignedTinyInteger('sequence');$t->decimal('amount',14,2);$t->date('due_on');$t->string('status',20)->default('pending');$t->timestamps();$t->unique(['fee_invoice_id','sequence']);});
  Schema::create('scholarships',function(Blueprint $t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('discount_type',20);$t->decimal('discount_value',14,2);$t->date('starts_on')->nullable();$t->date('ends_on')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('scholarship_student',function(Blueprint $t){$t->foreignId('scholarship_id')->constrained()->cascadeOnDelete();$t->foreignId('student_id')->constrained()->cascadeOnDelete();$t->foreignId('approved_by')->constrained('users')->restrictOnDelete();$t->timestamps();$t->primary(['scholarship_id','student_id']);});
  Schema::create('expenses',function(Blueprint $t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->string('reference')->unique();$t->string('category',60);$t->string('description');$t->decimal('amount',14,2);$t->char('currency',3)->default('NGN');$t->date('expense_date');$t->string('status',20)->default('pending');$t->foreignId('submitted_by')->constrained('users')->restrictOnDelete();$t->foreignId('approved_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('approved_at')->nullable();$t->timestamps();$t->index(['school_id','expense_date','status']);});
  Schema::create('payroll_runs',function(Blueprint $t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->string('reference')->unique();$t->date('period_start');$t->date('period_end');$t->string('status',20)->default('draft');$t->decimal('gross_total',14,2)->default(0);$t->decimal('deduction_total',14,2)->default(0);$t->decimal('net_total',14,2)->default(0);$t->foreignId('created_by')->constrained('users')->restrictOnDelete();$t->timestamp('processed_at')->nullable();$t->timestamps();$t->index(['school_id','period_start','period_end']);});
  Schema::create('payroll_items',function(Blueprint $t){$t->id();$t->foreignId('payroll_run_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->restrictOnDelete();$t->decimal('gross_amount',14,2);$t->decimal('deduction_amount',14,2)->default(0);$t->decimal('net_amount',14,2);$t->json('breakdown')->nullable();$t->string('status',20)->default('pending');$t->timestamps();$t->unique(['payroll_run_id','user_id']);});
  Schema::table('payments',function(Blueprint $t){$t->foreignId('fee_invoice_id')->nullable()->after('student_id')->constrained()->nullOnDelete();$t->string('provider')->nullable()->after('payment_method');$t->string('provider_reference')->nullable()->unique()->after('provider');$t->json('provider_payload')->nullable()->after('provider_reference');});
 }
 public function down():void{Schema::table('payments',function(Blueprint $t){$t->dropConstrainedForeignId('fee_invoice_id');$t->dropColumn(['provider','provider_reference','provider_payload']);});Schema::dropIfExists('payroll_items');Schema::dropIfExists('payroll_runs');Schema::dropIfExists('expenses');Schema::dropIfExists('scholarship_student');Schema::dropIfExists('scholarships');Schema::dropIfExists('installment_schedules');Schema::dropIfExists('fee_invoice_items');Schema::dropIfExists('fee_invoices');}
};
