<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('hostel_buildings', function (Blueprint $t) { $t->id(); $t->foreignId('school_id')->constrained()->cascadeOnDelete(); $t->foreignId('campus_id')->nullable()->constrained()->nullOnDelete(); $t->string('name'); $t->string('gender',20)->default('mixed'); $t->boolean('is_active')->default(true); $t->timestamps(); $t->unique(['school_id','name']); });
        Schema::create('hostel_rooms', function (Blueprint $t) { $t->id(); $t->foreignId('school_id')->constrained()->cascadeOnDelete(); $t->foreignId('hostel_building_id')->constrained()->cascadeOnDelete(); $t->string('room_number'); $t->unsignedSmallInteger('capacity'); $t->decimal('fee',14,2)->default(0); $t->string('status',20)->default('available'); $t->timestamps(); $t->unique(['hostel_building_id','room_number']); });
        Schema::create('hostel_allocations', function (Blueprint $t) { $t->id(); $t->foreignId('school_id')->constrained()->cascadeOnDelete(); $t->foreignId('hostel_room_id')->constrained()->restrictOnDelete(); $t->foreignId('student_id')->constrained()->cascadeOnDelete(); $t->foreignId('academic_term_id')->nullable()->constrained()->nullOnDelete(); $t->foreignId('allocated_by')->constrained('users')->restrictOnDelete(); $t->date('starts_on'); $t->date('ends_on')->nullable(); $t->string('status',20)->default('active'); $t->timestamps(); $t->unique(['student_id','academic_term_id']); });

        Schema::create('library_items', function (Blueprint $t) { $t->id(); $t->foreignId('school_id')->constrained()->cascadeOnDelete(); $t->string('title'); $t->string('author')->nullable(); $t->string('isbn')->nullable(); $t->string('barcode'); $t->string('category')->nullable(); $t->unsignedInteger('copies_total')->default(1); $t->unsignedInteger('copies_available')->default(1); $t->string('status',20)->default('active'); $t->timestamps(); $t->unique(['school_id','barcode']); });
        Schema::create('library_loans', function (Blueprint $t) { $t->id(); $t->foreignId('school_id')->constrained()->cascadeOnDelete(); $t->foreignId('library_item_id')->constrained()->restrictOnDelete(); $t->foreignId('student_id')->constrained()->cascadeOnDelete(); $t->foreignId('issued_by')->constrained('users')->restrictOnDelete(); $t->timestamp('borrowed_at'); $t->date('due_on'); $t->timestamp('returned_at')->nullable(); $t->decimal('fine_amount',14,2)->default(0); $t->string('status',20)->default('borrowed'); $t->timestamps(); $t->index(['school_id','status','due_on']); });

        Schema::create('transport_routes', function (Blueprint $t) { $t->id(); $t->foreignId('school_id')->constrained()->cascadeOnDelete(); $t->string('name'); $t->string('code'); $t->string('start_point'); $t->string('end_point'); $t->json('stops')->nullable(); $t->decimal('term_fee',14,2)->default(0); $t->boolean('is_active')->default(true); $t->timestamps(); $t->unique(['school_id','code']); });
        Schema::create('transport_vehicles', function (Blueprint $t) { $t->id(); $t->foreignId('school_id')->constrained()->cascadeOnDelete(); $t->string('registration_number'); $t->string('make_model')->nullable(); $t->unsignedSmallInteger('capacity'); $t->string('driver_name'); $t->string('driver_phone'); $t->string('status',20)->default('active'); $t->timestamps(); $t->unique(['school_id','registration_number']); });
        Schema::create('transport_assignments', function (Blueprint $t) { $t->id(); $t->foreignId('school_id')->constrained()->cascadeOnDelete(); $t->foreignId('student_id')->constrained()->cascadeOnDelete(); $t->foreignId('transport_route_id')->constrained()->restrictOnDelete(); $t->foreignId('transport_vehicle_id')->nullable()->constrained()->nullOnDelete(); $t->foreignId('academic_term_id')->nullable()->constrained()->nullOnDelete(); $t->string('pickup_stop'); $t->string('dropoff_stop'); $t->string('status',20)->default('active'); $t->timestamps(); $t->unique(['student_id','academic_term_id']); });

        Schema::create('wallets', function (Blueprint $t) { $t->id(); $t->foreignId('school_id')->constrained()->cascadeOnDelete(); $t->foreignId('student_id')->constrained()->cascadeOnDelete(); $t->char('currency',3)->default('NGN'); $t->decimal('balance',14,2)->default(0); $t->boolean('is_active')->default(true); $t->timestamps(); $t->unique(['school_id','student_id']); });
        Schema::create('wallet_transactions', function (Blueprint $t) { $t->id(); $t->uuid('public_id')->unique(); $t->foreignId('school_id')->constrained()->cascadeOnDelete(); $t->foreignId('wallet_id')->constrained()->restrictOnDelete(); $t->string('type',20); $t->decimal('amount',14,2); $t->decimal('balance_before',14,2); $t->decimal('balance_after',14,2); $t->string('reference')->unique(); $t->string('description'); $t->string('counterparty')->nullable(); $t->foreignId('initiated_by')->nullable()->constrained('users')->nullOnDelete(); $t->json('metadata')->nullable(); $t->timestamps(); $t->index(['school_id','wallet_id','created_at']); });

        Schema::create('marketplace_vendors', function (Blueprint $t) { $t->id(); $t->foreignId('school_id')->constrained()->cascadeOnDelete(); $t->string('name'); $t->string('email')->nullable(); $t->string('phone')->nullable(); $t->string('status',20)->default('active'); $t->timestamps(); });
        Schema::create('marketplace_products', function (Blueprint $t) { $t->id(); $t->foreignId('school_id')->constrained()->cascadeOnDelete(); $t->foreignId('marketplace_vendor_id')->nullable()->constrained()->nullOnDelete(); $t->string('name'); $t->string('sku'); $t->text('description')->nullable(); $t->decimal('price',14,2); $t->unsignedInteger('stock_quantity')->default(0); $t->boolean('is_active')->default(true); $t->timestamps(); $t->unique(['school_id','sku']); });
        Schema::create('marketplace_orders', function (Blueprint $t) { $t->id(); $t->string('order_number')->unique(); $t->foreignId('school_id')->constrained()->cascadeOnDelete(); $t->foreignId('student_id')->constrained()->cascadeOnDelete(); $t->foreignId('wallet_transaction_id')->nullable()->constrained()->nullOnDelete(); $t->decimal('total',14,2); $t->string('status',20)->default('pending'); $t->foreignId('created_by')->constrained('users')->restrictOnDelete(); $t->timestamps(); });
        Schema::create('marketplace_order_items', function (Blueprint $t) { $t->id(); $t->foreignId('marketplace_order_id')->constrained()->cascadeOnDelete(); $t->foreignId('marketplace_product_id')->constrained()->restrictOnDelete(); $t->unsignedInteger('quantity'); $t->decimal('unit_price',14,2); $t->decimal('total',14,2); $t->timestamps(); });
    }
    public function down(): void
    {
        foreach (['marketplace_order_items','marketplace_orders','marketplace_products','marketplace_vendors','wallet_transactions','wallets','transport_assignments','transport_vehicles','transport_routes','library_loans','library_items','hostel_allocations','hostel_rooms','hostel_buildings'] as $table) Schema::dropIfExists($table);
    }
};
