@extends('layouts.app')
@section('title','Institution structure')
@section('page_title','Institution structure')
@section('content')
@php $tabs=['campuses'=>'Campuses','faculties'=>'Faculties','departments'=>'Departments','courses'=>'Courses','registrations'=>'Course registration']; @endphp
<div class="space-y-6"><div><p class="text-sm font-bold uppercase tracking-wider text-[#3A7B72]">Academic foundation</p><h2 class="text-3xl font-extrabold">Institution structure</h2><p class="text-slate-500">Manage multiple campuses and the academic hierarchy within this school.</p></div>
<nav class="flex flex-wrap gap-2">@foreach($tabs as $key=>$label)<a href="{{ route('academic-structure.index',['section'=>$key]) }}" class="rounded-xl px-4 py-2 text-sm font-bold {{ $section===$key?'bg-[#06322C] text-white':'bg-white text-slate-500' }}">{{ $label }}</a>@endforeach</nav>
@if($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{{ $errors->first() }}</div>@endif
@if($section==='campuses')
<div class="grid gap-6 xl:grid-cols-[.7fr_1.3fr]"><form method="POST" action="{{ route('academic-structure.campuses.store') }}" class="space-y-3 rounded-2xl bg-white p-6 shadow-sm">@csrf<h3 class="font-extrabold">Add campus</h3><input name="name" required placeholder="Campus name" class="w-full rounded-xl px-4 py-3"><input name="code" required placeholder="Campus code" class="w-full rounded-xl px-4 py-3"><div class="grid grid-cols-2 gap-3"><input type="email" name="email" placeholder="Email" class="rounded-xl px-4 py-3"><input name="phone" placeholder="Phone" class="rounded-xl px-4 py-3"></div><textarea name="address" placeholder="Address" class="w-full rounded-xl px-4 py-3"></textarea><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_main" value="1"> Main campus</label><button class="w-full rounded-xl bg-[#06322C] py-3 font-bold text-white">Create campus</button></form><div class="grid gap-3 sm:grid-cols-2">@forelse($campuses as $item)<article class="rounded-2xl bg-white p-5 shadow-sm"><div class="flex justify-between"><div><strong>{{ $item->name }}</strong><small class="block text-slate-400">{{ $item->code }}</small></div>@if($item->is_main)<span class="h-fit rounded-full bg-[#E7F5F1] px-3 py-1 text-xs font-bold text-[#06322C]">Main</span>@endif</div><p class="mt-5 text-sm text-slate-500">{{ $item->faculties_count }} faculties · {{ $item->departments_count }} departments</p></article>@empty<div class="rounded-2xl bg-white p-10 text-center text-slate-400">No campuses created.</div>@endforelse</div></div>
@elseif($section==='faculties')
<x-structure-workspace title="Add faculty" action="{{ route('academic-structure.faculties.store') }}"><x-slot:form><input name="name" required placeholder="Faculty name" class="w-full rounded-xl px-4 py-3"><input name="code" required placeholder="Faculty code" class="w-full rounded-xl px-4 py-3"><select name="campus_id" class="w-full rounded-xl px-4 py-3"><option value="">No campus</option>@foreach($campuses as $campus)<option value="{{ $campus->id }}">{{ $campus->name }}</option>@endforeach</select><select name="dean_id" class="w-full rounded-xl px-4 py-3"><option value="">No dean assigned</option>@foreach($staff as $person)<option value="{{ $person->id }}">{{ $person->name }}</option>@endforeach</select></x-slot:form><x-slot:items>@foreach($faculties as $item)<x-structure-card :title="$item->name" :code="$item->code" :meta="($item->campus?->name ?? 'All campuses').' · '.$item->departments_count.' departments'" />@endforeach</x-slot:items></x-structure-workspace>
@elseif($section==='departments')
<x-structure-workspace title="Add department" action="{{ route('academic-structure.departments.store') }}"><x-slot:form><input name="name" required placeholder="Department name" class="w-full rounded-xl px-4 py-3"><input name="code" required placeholder="Department code" class="w-full rounded-xl px-4 py-3"><select name="faculty_id" class="w-full rounded-xl px-4 py-3"><option value="">No faculty</option>@foreach($faculties as $faculty)<option value="{{ $faculty->id }}">{{ $faculty->name }}</option>@endforeach</select><select name="campus_id" class="w-full rounded-xl px-4 py-3"><option value="">No campus</option>@foreach($campuses as $campus)<option value="{{ $campus->id }}">{{ $campus->name }}</option>@endforeach</select><select name="head_id" class="w-full rounded-xl px-4 py-3"><option value="">No department head</option>@foreach($staff as $person)<option value="{{ $person->id }}">{{ $person->name }}</option>@endforeach</select></x-slot:form><x-slot:items>@foreach($departments as $item)<x-structure-card :title="$item->name" :code="$item->code" :meta="($item->faculty?->name ?? 'Independent').' · '.$item->courses_count.' courses'" />@endforeach</x-slot:items></x-structure-workspace>
@elseif($section==='courses')
<x-structure-workspace title="Add course" action="{{ route('academic-structure.courses.store') }}"><x-slot:form><input name="name" required placeholder="Course name" class="w-full rounded-xl px-4 py-3"><input name="code" required placeholder="Course code" class="w-full rounded-xl px-4 py-3"><select name="department_id" class="w-full rounded-xl px-4 py-3"><option value="">No department</option>@foreach($departments as $department)<option value="{{ $department->id }}">{{ $department->name }}</option>@endforeach</select><div class="grid grid-cols-2 gap-3"><input type="number" name="credit_units" value="1" min="1" max="30" required placeholder="Units" class="rounded-xl px-4 py-3"><input type="number" name="level" min="1" placeholder="Level" class="rounded-xl px-4 py-3"></div><textarea name="description" placeholder="Description" class="w-full rounded-xl px-4 py-3"></textarea></x-slot:form><x-slot:items>@foreach($courses as $item)<x-structure-card :title="$item->name" :code="$item->code" :meta="$item->credit_units.' units · '.$item->registrations_count.' registrations'" />@endforeach</x-slot:items></x-structure-workspace>
@else
<div class="grid gap-6 xl:grid-cols-[.7fr_1.3fr]"><form method="POST" action="{{ route('academic-structure.registrations.store') }}" class="space-y-3 rounded-2xl bg-white p-6 shadow-sm">@csrf<h3 class="font-extrabold">Register a course</h3><select name="student_id" required class="w-full rounded-xl px-4 py-3"><option value="">Select student</option>@foreach($students as $student)<option value="{{ $student->id }}">{{ $student->full_name }}</option>@endforeach</select><select name="course_id" required class="w-full rounded-xl px-4 py-3"><option value="">Select course</option>@foreach($courses as $course)<option value="{{ $course->id }}">{{ $course->code }} · {{ $course->name }}</option>@endforeach</select><select name="academic_term_id" required class="w-full rounded-xl px-4 py-3"><option value="">Select academic term</option>@foreach($terms as $term)<option value="{{ $term->id }}">{{ $term->academicYear->name }} · {{ $term->name }}</option>@endforeach</select><button class="w-full rounded-xl bg-[#06322C] py-3 font-bold text-white">Register course</button></form><section class="overflow-hidden rounded-2xl bg-white shadow-sm"><div class="divide-y">@forelse($registrations as $item)<div class="flex items-center justify-between gap-4 p-4"><div><strong>{{ $item->student->full_name }}</strong><small class="block text-slate-400">{{ $item->course->code }} · {{ $item->course->name }}</small></div><span class="text-xs text-slate-500">{{ $item->academicTerm->name }}</span></div>@empty<p class="p-10 text-center text-slate-400">No course registrations yet.</p>@endforelse</div></section></div>
@endif</div>
@endsection
