@extends('layouts.app')
@section('title','Executive analytics')
@section('page_title','Executive analytics')
@section('content')
<div class="space-y-6">
 <div class="flex flex-wrap items-end justify-between gap-4"><div><h2 class="text-3xl font-extrabold text-[#06322C]">School intelligence</h2><p class="text-slate-500">Explainable operational analytics and student risk signals.</p></div><form method="POST" action="{{ route('analytics.recalculate') }}">@csrf<button class="rounded-xl bg-[#06322C] px-5 py-3 font-bold text-white">Recalculate success scores</button></form></div>
 <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
  @foreach([['Revenue collected',number_format($kpis['collected'],2),$kpis['collection_rate'].'% of invoiced'],['Outstanding fees',number_format($kpis['outstanding'],2),'Across issued invoices'],['Student attendance',$kpis['attendance_rate']===null?'No data':$kpis['attendance_rate'].'%','Last 30 days'],['High-risk students',$kpis['at_risk'],$kpis['average_success']===null?'Run first calculation':'Average score '.$kpis['average_success']]] as [$label,$value,$note])<div class="rounded-2xl bg-white p-5 shadow-sm"><small class="font-semibold text-slate-400">{{ $label }}</small><strong class="mt-2 block text-2xl text-[#06322C]">{{ $value }}</strong><small class="text-slate-500">{{ $note }}</small></div>@endforeach
 </div>
 <div class="grid gap-6 xl:grid-cols-2"><div class="rounded-2xl bg-white p-6 shadow-sm"><h3 class="font-extrabold">Revenue trend</h3><div class="h-64"><canvas id="revenueChart"></canvas></div></div><div class="rounded-2xl bg-white p-6 shadow-sm"><h3 class="font-extrabold">Enrollment trend</h3><div class="h-64"><canvas id="enrollmentChart"></canvas></div></div></div>
 <div class="grid gap-6 xl:grid-cols-3">
  <div class="rounded-2xl bg-white p-6 shadow-sm xl:col-span-2"><div class="flex justify-between"><div><h3 class="font-extrabold">Revenue forecast</h3><p class="text-sm text-slate-500">Three-month projection using recent receipts and capped month-over-month momentum.</p></div><span class="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">{{ number_format($growth*100,1) }}% momentum</span></div><div class="h-64"><canvas id="forecastChart"></canvas></div></div>
  <div class="rounded-2xl bg-white p-6 shadow-sm"><h3 class="font-extrabold">Outstanding fee aging</h3><div class="mt-5 space-y-4">@foreach($aging as $label=>$value)<div><div class="flex justify-between text-sm"><span>{{$label}}</span><strong>{{number_format($value,2)}}</strong></div><div class="mt-1 h-2 rounded-full bg-slate-100"><div class="h-2 rounded-full bg-[#3A7B72]" style="width:{{ $aging->max()>0 ? max(3,$value/$aging->max()*100) : 0 }}%"></div></div></div>@endforeach</div></div>
 </div>
 <div class="grid gap-6 xl:grid-cols-2"><div class="rounded-2xl bg-white p-6 shadow-sm"><h3 class="font-extrabold">Student attendance trend</h3><div class="h-64"><canvas id="attendanceChart"></canvas></div></div><div class="rounded-2xl bg-white p-6 shadow-sm"><h3 class="font-extrabold">GPA / grade distribution</h3><div class="h-64"><canvas id="gradeChart"></canvas></div></div></div>
 <div class="overflow-hidden rounded-2xl bg-white shadow-sm"><div class="p-6"><h3 class="text-lg font-extrabold">Dropout-risk forecast</h3><p class="text-sm text-slate-500">Explainable early-warning probability derived from the Student Success Score and recent decline. It supports human review; it does not make enrollment decisions.</p></div><table class="w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-400"><tr><th class="p-4">Student</th><th>Probability</th><th>Risk</th><th>Trend</th><th>Evidence</th></tr></thead><tbody class="divide-y">@forelse($risk as $item)<tr><td class="p-4"><strong>{{$item['student']->full_name}}</strong><small class="block text-slate-400">{{$item['student']->class?->full_name}}</small></td><td class="font-extrabold">{{$item['probability']}}%</td><td><span class="rounded-full px-3 py-1 text-xs font-bold {{$item['level']==='high'?'bg-red-100 text-red-700':($item['level']==='medium'?'bg-amber-100 text-amber-700':'bg-emerald-100 text-emerald-700')}}">{{ucfirst($item['level'])}}</span></td><td>{{$item['trend']>0?'+':''}}{{$item['trend']}}</td><td>{{collect($item['factors'])->pluck('metric')->join(', ') ?: 'No active factor'}}</td></tr>@empty<tr><td colspan="5" class="p-10 text-center text-slate-400">Calculate Student Success Scores to generate the risk forecast.</td></tr>@endforelse</tbody></table></div>
 <div class="grid gap-6 xl:grid-cols-[1fr_380px]">
  <div class="overflow-hidden rounded-2xl bg-white shadow-sm"><div class="flex items-center justify-between p-6"><div><h3 class="text-lg font-extrabold">Student Success Score™</h3><p class="text-sm text-slate-500">40% academics · 20% attendance · 15% assignments · 15% behaviour · 10% leadership</p></div><small class="text-slate-400">{{ $latestDate ? \Carbon\Carbon::parse($latestDate)->format('M j, Y') : 'Not calculated' }}</small></div><table class="w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-400"><tr><th class="p-4">Student</th><th>Score</th><th>Trend</th><th>Risk</th><th>Primary signal</th></tr></thead><tbody class="divide-y">@forelse($scores as $score)<tr><td class="p-4"><strong>{{ $score->student->full_name }}</strong><small class="block text-slate-400">{{ $score->student->class?->full_name }}</small></td><td class="font-extrabold">{{ $score->score }}</td><td class="{{ $score->trend<0?'text-red-600':'text-emerald-600' }}">{{ $score->trend>0?'+':'' }}{{ $score->trend }}</td><td><span class="rounded-full px-3 py-1 text-xs font-bold {{ $score->risk_level==='high'?'bg-red-100 text-red-700':($score->risk_level==='medium'?'bg-amber-100 text-amber-700':'bg-emerald-100 text-emerald-700') }}">{{ ucfirst($score->risk_level) }}</span></td><td>{{ data_get($score->risk_factors,'0.metric','No active risk') }}</td></tr>@empty<tr><td colspan="5" class="p-12 text-center text-slate-400">Run the first score calculation to populate cohort intelligence.</td></tr>@endforelse</tbody></table></div>
  <div class="space-y-6"><div class="rounded-2xl bg-[#06322C] p-6 text-white"><small class="font-bold uppercase tracking-widest text-[#7ED3C4]">Executive brief</small><h3 class="mt-2 text-xl font-extrabold">This week's priorities</h3><ul class="mt-4 space-y-3 text-sm text-emerald-50"><li>• {{ $kpis['at_risk'] }} students currently need high-priority intervention.</li><li>• Fee collection is {{ $kpis['collection_rate'] }}%; {{ number_format($kpis['outstanding'],2) }} remains outstanding.</li><li>• Teacher punctuality: {{ $kpis['teacher_punctuality']===null?'record attendance to establish a baseline':$kpis['teacher_punctuality'].'%' }}.</li></ul></div>
   <form method="POST" action="{{ route('analytics.signals.store') }}" class="space-y-3 rounded-2xl bg-white p-6 shadow-sm">@csrf<h3 class="font-extrabold">Record development signal</h3><select name="student_id" required class="w-full rounded-xl border-slate-200">@foreach($students as $student)<option value="{{ $student->id }}">{{ $student->full_name }}</option>@endforeach</select><div class="grid grid-cols-2 gap-2"><select name="category" class="rounded-xl border-slate-200"><option value="behaviour">Behaviour</option><option value="leadership">Leadership</option></select><input type="number" name="score" min="0" max="100" required placeholder="Score / 100" class="rounded-xl border-slate-200"></div><input type="date" name="occurred_on" value="{{ now()->toDateString() }}" required class="w-full rounded-xl border-slate-200"><textarea name="note" required placeholder="Evidence-based note" class="w-full rounded-xl border-slate-200"></textarea><button class="w-full rounded-xl bg-[#06322C] py-3 font-bold text-white">Record signal</button></form>
  </div>
 </div>
 <div class="grid gap-6 xl:grid-cols-2"><div class="rounded-2xl bg-white p-6 shadow-sm"><h3 class="mb-4 text-lg font-extrabold">Open interventions</h3><div class="space-y-3">@forelse($interventions as $item)<div class="flex items-start justify-between rounded-xl bg-slate-50 p-4"><div><strong>{{ $item->student->full_name }} · {{ $item->title }}</strong><small class="block text-slate-500">{{ $item->assignee?->name ?? 'Unassigned' }} · due {{ $item->due_on?->format('M j') ?? 'not set' }}</small></div><form method="POST" action="{{ route('analytics.interventions.complete',$item) }}">@csrf<button class="text-sm font-bold text-[#3A7B72]">Complete</button></form></div>@empty<p class="text-sm text-slate-400">No open interventions.</p>@endforelse</div></div><form method="POST" action="{{ route('analytics.interventions.store') }}" class="space-y-3 rounded-2xl bg-white p-6 shadow-sm">@csrf<h3 class="text-lg font-extrabold">Create intervention</h3><div class="grid gap-3 sm:grid-cols-2"><select name="student_id" required class="rounded-xl border-slate-200">@foreach($students as $student)<option value="{{ $student->id }}">{{ $student->full_name }}</option>@endforeach</select><select name="assigned_to" class="rounded-xl border-slate-200"><option value="">Unassigned</option>@foreach($teachers as $teacher)<option value="{{ $teacher->id }}">{{ $teacher->name }}</option>@endforeach</select></div><input name="title" required placeholder="Intervention title" class="w-full rounded-xl border-slate-200"><textarea name="action_plan" required placeholder="Measurable action plan" class="w-full rounded-xl border-slate-200"></textarea><input type="date" name="due_on" class="w-full rounded-xl border-slate-200"><button class="w-full rounded-xl bg-[#06322C] py-3 font-bold text-white">Create intervention</button></form></div>
 <form method="POST" action="{{ route('analytics.staff-attendance.store') }}" class="grid gap-3 rounded-2xl bg-white p-6 shadow-sm md:grid-cols-6">@csrf<div class="md:col-span-6"><h3 class="text-lg font-extrabold">Teacher attendance</h3><p class="text-sm text-slate-500">Capture punctuality data for the executive KPI.</p></div><select name="user_id" required class="rounded-xl border-slate-200 md:col-span-2">@foreach($teachers as $teacher)<option value="{{ $teacher->id }}">{{ $teacher->name }}</option>@endforeach</select><input type="date" name="attendance_date" value="{{ now()->toDateString() }}" required class="rounded-xl border-slate-200"><select name="status" class="rounded-xl border-slate-200"><option>present</option><option>late</option><option>absent</option><option>excused</option></select><input type="time" name="checked_in_at" class="rounded-xl border-slate-200"><button class="rounded-xl bg-[#06322C] px-4 font-bold text-white">Save attendance</button></form>
</div>
@push('scripts')<script>const chart=(id,rows,color)=>new Chart(document.getElementById(id),{type:'line',data:{labels:rows.map(x=>x.label),datasets:[{data:rows.map(x=>x.value),borderColor:color,backgroundColor:color+'22',fill:true,tension:.35}]},options:{maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true}}}});chart('revenueChart',@json($monthlyRevenue),'#06322C');chart('enrollmentChart',@json($monthlyEnrollment),'#3A7B72');chart('forecastChart',@json($forecast),'#E47B50');chart('attendanceChart',@json($attendance),'#3A7B72');new Chart(document.getElementById('gradeChart'),{type:'doughnut',data:{labels:@json($distribution->keys()),datasets:[{data:@json($distribution->values()),backgroundColor:['#06322C','#3A7B72','#7ED3C4','#E9B949','#E47B50']}]},options:{maintainAspectRatio:false}});</script>@endpush
@endsection
