@extends('layouts.app')
@section('title','Campus Operations') @section('page_title','Campus Operations')
@section('content')
<div x-data="{tab:'hostel'}" class="space-y-6">
 <div class="rounded-2xl bg-gradient-to-r from-emerald-700 to-teal-600 p-6 text-white"><p class="text-xs font-bold uppercase tracking-[.2em] text-emerald-100">Unified operations</p><h1 class="mt-2 text-2xl font-bold">Run life beyond the classroom</h1><p class="mt-1 text-emerald-50">Hostels, circulation, transport, student wallets and campus commerce—with every record scoped to your institution.</p></div>
 @if(session('success'))<div class="rounded-xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{{ session('success') }}</div>@endif
 @if($errors->any())<div class="rounded-xl bg-red-50 p-4 text-sm text-red-700">{{ $errors->first() }}</div>@endif
 <div class="flex gap-2 overflow-x-auto">@foreach(['hostel'=>'Hostel','library'=>'Library','transport'=>'Transport','wallet'=>'Wallet','market'=>'Marketplace'] as $key=>$label)<button @click="tab='{{$key}}'" :class="tab==='{{$key}}'?'bg-emerald-700 text-white':'bg-white text-slate-600'" class="whitespace-nowrap rounded-xl px-4 py-2 text-sm font-bold">{{$label}}</button>@endforeach</div>
 <section x-show="tab==='hostel'" class="grid gap-5 lg:grid-cols-3">
  <x-campus-form title="Add hostel" action="{{route('campus.hostels.store')}}"><input name="name" placeholder="Building name" required><select name="gender"><option value="mixed">Mixed</option><option value="male">Male</option><option value="female">Female</option></select></x-campus-form>
  <x-campus-form title="Add room" action="{{route('campus.rooms.store')}}"><select name="hostel_building_id" required>@foreach($buildings as $b)<option value="{{$b->id}}">{{$b->name}}</option>@endforeach</select><input name="room_number" placeholder="Room number" required><input name="capacity" type="number" min="1" placeholder="Capacity" required><input name="fee" type="number" min="0" step=".01" placeholder="Fee"></x-campus-form>
  <x-campus-form title="Allocate student" action="{{route('campus.allocations.store')}}"><select name="student_id">@foreach($students as $s)<option value="{{$s->id}}">{{$s->first_name}} {{$s->last_name}}</option>@endforeach</select><select name="hostel_room_id">@foreach($buildings as $b)@foreach($b->rooms as $room)<option value="{{$room->id}}">{{$b->name}} · {{$room->room_number}}</option>@endforeach @endforeach</select><input type="date" name="starts_on" value="{{now()->toDateString()}}" required></x-campus-form>
 </section>
 <section x-show="tab==='library'" class="grid gap-5 lg:grid-cols-2"><x-campus-form title="Add library item" action="{{route('campus.library.items.store')}}"><input name="title" placeholder="Title" required><input name="author" placeholder="Author"><input name="barcode" placeholder="Barcode" required><input name="copies_total" type="number" min="1" value="1" required></x-campus-form><x-campus-form title="Check out item" action="{{route('campus.library.loans.store')}}"><select name="student_id">@foreach($students as $s)<option value="{{$s->id}}">{{$s->first_name}} {{$s->last_name}}</option>@endforeach</select><select name="library_item_id">@foreach($libraryItems as $i)<option value="{{$i->id}}">{{$i->title}} ({{$i->copies_available}} available)</option>@endforeach</select><input type="date" name="due_on" required></x-campus-form></section>
 <section x-show="tab==='transport'" class="grid gap-5 lg:grid-cols-3"><x-campus-form title="Add route" action="{{route('campus.transport.routes.store')}}"><input name="name" placeholder="Route name" required><input name="code" placeholder="Code" required><input name="start_point" placeholder="Start" required><input name="end_point" placeholder="End" required></x-campus-form><x-campus-form title="Add vehicle" action="{{route('campus.transport.vehicles.store')}}"><input name="registration_number" placeholder="Registration" required><input name="capacity" type="number" min="1" placeholder="Seats" required><input name="driver_name" placeholder="Driver" required><input name="driver_phone" placeholder="Phone" required></x-campus-form><x-campus-form title="Assign student" action="{{route('campus.transport.assignments.store')}}"><select name="student_id">@foreach($students as $s)<option value="{{$s->id}}">{{$s->first_name}} {{$s->last_name}}</option>@endforeach</select><select name="transport_route_id">@foreach($routes as $r)<option value="{{$r->id}}">{{$r->name}}</option>@endforeach</select><select name="transport_vehicle_id"><option value="">No vehicle</option>@foreach($vehicles as $v)<option value="{{$v->id}}">{{$v->registration_number}}</option>@endforeach</select><input name="pickup_stop" placeholder="Pickup stop" required><input name="dropoff_stop" placeholder="Drop-off stop" required></x-campus-form></section>
 <section x-show="tab==='wallet'" class="grid gap-5 lg:grid-cols-2"><x-campus-form title="Post wallet transaction" action="{{route('campus.wallets.transactions.store')}}"><select name="student_id">@foreach($students as $s)<option value="{{$s->id}}">{{$s->first_name}} {{$s->last_name}}</option>@endforeach</select><select name="type"><option value="credit">Credit</option><option value="debit">Debit</option></select><input name="amount" type="number" min=".01" step=".01" placeholder="Amount" required><input name="reference" placeholder="Unique reference" required><input name="description" placeholder="Description" required></x-campus-form><div class="rounded-2xl bg-white p-5"><h2 class="font-bold">Balances</h2>@forelse($wallets as $w)<div class="flex justify-between border-b py-3 text-sm"><span>{{$w->student->first_name}} {{$w->student->last_name}}</span><b>₦{{number_format($w->balance,2)}}</b></div>@empty<p class="mt-4 text-sm text-slate-400">No wallets yet.</p>@endforelse</div></section>
 <section x-show="tab==='market'" class="grid gap-5 lg:grid-cols-3"><x-campus-form title="Add vendor" action="{{route('campus.marketplace.vendors.store')}}"><input name="name" placeholder="Vendor name" required><input name="email" type="email" placeholder="Email"><input name="phone" placeholder="Phone"></x-campus-form><x-campus-form title="Add product" action="{{route('campus.marketplace.products.store')}}"><select name="marketplace_vendor_id"><option value="">School stock</option>@foreach($vendors as $v)<option value="{{$v->id}}">{{$v->name}}</option>@endforeach</select><input name="name" placeholder="Product" required><input name="sku" placeholder="SKU" required><input name="price" type="number" min="0" step=".01" placeholder="Price" required><input name="stock_quantity" type="number" min="0" placeholder="Stock" required></x-campus-form><x-campus-form title="Wallet purchase" action="{{route('campus.marketplace.orders.store')}}"><select name="student_id">@foreach($students as $s)<option value="{{$s->id}}">{{$s->first_name}} {{$s->last_name}}</option>@endforeach</select><select name="items[0][product_id]">@foreach($products as $p)<option value="{{$p->id}}">{{$p->name}} · ₦{{number_format($p->price,2)}}</option>@endforeach</select><input name="items[0][quantity]" type="number" min="1" value="1" required></x-campus-form></section>
</div>
@endsection
