@extends('layouts.app')
@section('title','Platform overview') @section('page_title','Platform overview')
@section('content')
<div class="space-y-6">
 <div><h2 class="text-3xl font-extrabold text-[#06322C]">Network overview</h2><p class="text-slate-500">Live operational and commercial health across every SchoolOS institution.</p></div>
 <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach([['Schools',$stats['tenants']],['Active schools',$stats['active']],['Students',number_format($stats['students'])],['Teachers',number_format($stats['teachers'])],['Parents',number_format($stats['parents'])],['Product revenue','₦'.number_format($stats['revenue'],2)],['Estimated MRR','₦'.number_format($stats['monthly_recurring_revenue'],2)]] as [$label,$value])<div class="rounded-2xl bg-white p-6 shadow-sm"><small class="text-slate-400">{{ $label }}</small><strong class="mt-2 block text-2xl text-[#06322C]">{{ $value }}</strong></div>@endforeach</div>
 <div class="grid gap-6 lg:grid-cols-2"><section class="rounded-2xl bg-white p-6 shadow-sm"><div class="flex justify-between"><h3 class="text-lg font-extrabold text-[#06322C]">Institution health</h3><a href="{{ route('platform.schools.index') }}" class="text-sm font-bold text-[#3A7B72]">Manage schools →</a></div><div class="mt-4 divide-y">@foreach($schools->take(8) as $school)<div class="flex items-center justify-between py-3"><span><strong>{{ $school->name }}</strong><small class="block text-slate-400">{{ $school->students_count }} students · {{ $school->teachers_count }} teachers</small></span><span class="rounded-full px-3 py-1 text-xs font-bold {{ $school->is_active?'bg-emerald-100 text-emerald-700':'bg-red-100 text-red-700' }}">{{ $school->is_active?'Active':'Inactive' }}</span></div>@endforeach</div></section><section class="rounded-2xl bg-white p-6 shadow-sm"><div class="flex justify-between"><h3 class="text-lg font-extrabold text-[#06322C]">Recent product payments</h3><a href="{{ route('platform.payments.index') }}" class="text-sm font-bold text-[#3A7B72]">View ledger →</a></div><div class="mt-4 divide-y">@forelse($payments->take(8) as $payment)<div class="flex justify-between py-3 text-sm"><span><strong>{{ $payment->school?->name }}</strong><small class="block text-slate-400">{{ $payment->reference }}</small></span><strong class="text-emerald-700">{{ $payment->currency }} {{ number_format($payment->amount,2) }}</strong></div>@empty<p class="py-10 text-center text-slate-400">No subscription payments recorded.</p>@endforelse</div></section></div>
</div>
@endsection
