@extends('layouts.app')
@section('title','Product payments') @section('page_title','Product payments')
@section('content')
<div class="space-y-6">
 <div><h2 class="text-3xl font-extrabold text-[#06322C]">Subscription revenue</h2><p class="text-slate-500">Payments made by institutions for the SchoolOS product—not student fee collections.</p></div>
 <div class="grid gap-4 sm:grid-cols-2"><div class="rounded-2xl bg-[#06322C] p-6 text-white shadow-sm"><small class="text-emerald-200">Total product revenue</small><strong class="mt-2 block text-3xl">₦{{ number_format($stats['revenue'],2) }}</strong></div><div class="rounded-2xl bg-white p-6 shadow-sm"><small class="text-slate-400">Estimated monthly recurring revenue</small><strong class="mt-2 block text-3xl text-[#06322C]">₦{{ number_format($stats['monthly_recurring_revenue'],2) }}</strong></div></div>
 <section class="overflow-hidden rounded-2xl bg-white shadow-sm"><div class="border-b p-5"><h3 class="font-extrabold">Payment ledger</h3><p class="text-sm text-slate-400">Latest tenant subscription transactions.</p></div><div class="overflow-x-auto"><table class="w-full min-w-[760px] text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-400"><tr><th class="p-4">School</th><th>Reference</th><th>Provider</th><th>Paid at</th><th>Status</th><th class="text-right">Amount</th></tr></thead><tbody class="divide-y">@forelse($payments as $payment)<tr><td class="p-4 font-bold text-[#06322C]">{{ $payment->school?->name }}</td><td>{{ $payment->reference }}</td><td>{{ ucfirst($payment->provider) }}</td><td>{{ $payment->paid_at?->format('M j, Y H:i') ?? '—' }}</td><td><span class="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">{{ ucfirst($payment->status) }}</span></td><td class="text-right font-bold">{{ $payment->currency }} {{ number_format($payment->amount,2) }}</td></tr>@empty<tr><td colspan="6" class="p-12 text-center text-slate-400">No product subscription payments recorded.</td></tr>@endforelse</tbody></table></div></section>
</div>
@endsection
