@extends('layouts.app')
@section('title','Platform users') @section('page_title','Platform users')
@section('content')
<div class="space-y-6" x-data="{addUser:false,addStudent:false}">
 <div class="flex flex-wrap items-end justify-between gap-3"><div><h2 class="text-3xl font-extrabold text-[#06322C]">Users and students</h2><p class="text-slate-500">Provision teachers, parents, and students into the correct school.</p></div><div class="flex gap-2"><button @click="addUser=!addUser" class="rounded-xl border border-[#06322C] px-4 py-3 font-bold text-[#06322C]">+ Teacher / parent</button><button @click="addStudent=!addStudent" class="rounded-xl bg-[#06322C] px-4 py-3 font-bold text-white">+ Student</button></div></div>
 <form x-show="addUser" method="POST" action="{{ route('platform.users.store') }}" class="grid gap-3 rounded-2xl bg-white p-6 shadow-sm md:grid-cols-3">@csrf<h3 class="text-lg font-extrabold md:col-span-3">New role-based account</h3><select name="school_id" required class="rounded-xl px-4 py-3"><option value="">Select school</option>@foreach($allSchools as $school)<option value="{{ $school->id }}">{{ $school->name }}</option>@endforeach</select><select name="role" required class="rounded-xl px-4 py-3">@foreach(['school_admin'=>'School admin','principal'=>'Principal','vice_principal'=>'Vice principal','academic_admin'=>'Academic admin','bursar'=>'Bursar','teacher'=>'Teacher','parent'=>'Parent'] as $value=>$label)<option value="{{$value}}">{{$label}}</option>@endforeach</select><input name="name" required placeholder="Full name" class="rounded-xl px-4 py-3"><input type="email" name="email" required placeholder="Email" class="rounded-xl px-4 py-3"><input name="phone" placeholder="Phone" class="rounded-xl px-4 py-3"><input type="password" name="password" minlength="8" required placeholder="Temporary password" class="rounded-xl px-4 py-3"><select name="student_ids[]" multiple class="rounded-xl px-4 py-3 md:col-span-2"><option disabled>For parents: select linked students</option>@foreach($students as $student)<option value="{{ $student->id }}">{{ $student->school?->name }} · {{ $student->full_name }}</option>@endforeach</select><button class="rounded-xl bg-[#06322C] font-bold text-white">Create account</button></form>
 <form x-show="addStudent" method="POST" action="{{ route('platform.students.store') }}" class="grid gap-3 rounded-2xl bg-white p-6 shadow-sm md:grid-cols-3">@csrf<h3 class="text-lg font-extrabold md:col-span-3">New student</h3><select name="school_id" required class="rounded-xl px-4 py-3"><option value="">Select school</option>@foreach($allSchools as $school)<option value="{{ $school->id }}">{{ $school->name }}</option>@endforeach</select><input name="first_name" required placeholder="First name" class="rounded-xl px-4 py-3"><input name="last_name" required placeholder="Last name" class="rounded-xl px-4 py-3"><input type="email" name="email" required placeholder="Student email" class="rounded-xl px-4 py-3"><input type="date" name="date_of_birth" required class="rounded-xl px-4 py-3"><select name="gender" class="rounded-xl px-4 py-3"><option value="male">Male</option><option value="female">Female</option><option value="other">Other</option></select><button class="rounded-xl bg-[#06322C] py-3 font-bold text-white md:col-span-3">Add student</button></form>
 <section class="rounded-2xl bg-white p-6 shadow-sm"><h3 class="text-lg font-extrabold text-[#06322C]">Recent accounts</h3><div class="mt-4 divide-y">@forelse($users as $user)<div class="flex flex-wrap justify-between gap-2 py-3 text-sm"><span><strong>{{ $user->name }}</strong><small class="block text-slate-400">{{ $user->email }} · {{ $user->phone ?: 'No phone' }}</small></span><span class="text-right">{{ ucfirst(str_replace('_',' ',$user->role)) }}<small class="block text-slate-400">{{ $user->school?->name }}</small></span></div>@empty<p class="py-10 text-center text-slate-400">No school users yet.</p>@endforelse</div></section>
</div>
@endsection
